### ISSUE TITLE
Possible leader board integration for weekly programming competition

### ISSUE THREAD

**Issue by The-Royal-We** [MindsSociety/Compsoc-Website#3]
Good idea to work on is to integrate some sort of leaderboard that can be updated to show rankings in programming competitions.
I'll flesh this issue out more later

**Comment by Jiggins** [comment]
Just took a quick look into this, the Hackerrank API only offers two methods `GET languages` and `POST some submission`. There seems to be no way to get the leaderboard data from Hackerrank.

https://www.hackerrank.com/api/docs
